version: "3.7"

services:
  redis:
    container_name: redis
    image: redis:7.0.5
    ports:
      - "6379:6379"
    command: redis-server --requirepass danawa-pass
    environment:
      - TZ=Asia/Seoul